name: 🚀 Deploy website
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 18 LTS
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
        env:
          VITE_GOOGLEAPIS_YT_API_KEY: ${{ secrets.VITE_GOOGLEAPIS_YT_API_KEY }}
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: "./dist/"
          server-dir: "./freelivenews.rocks/"
