# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

  # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          #!/usr/bin/env sh

          # abort on errors
          set -e

          # build
          npm install
          npm run build

          # navigate into the build output directory
          cd dist

          # place .nojekyll to bypass Jekyll processing
          echo > .nojekyll

          # if you are deploying to a custom domain
          # echo 'www.example.com' > CNAME

          git init
          git checkout -B main
          git add -A
          git commit -m 'deploy'
          
          # if you are deploying to https://<USERNAME>.github.io/<REPO>
          git push -f git@github.com:omirete/free-live-news.git main:gh-pages

          cd -
