name: Update videos list and channel icons

on:
  schedule:
  # Runs every day at 01:12.
  - cron: "13 1 * * *"
  workflow_dispatch:
jobs:
  update-videos-and-channels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install requirements
      run: pip install -r python_requirements.txt
    - name: Update videos list
      run: python3 automations/update_news_videos_list.py -k ${{ secrets.PRIVATE_YT_API_KEY }} --ssh_host ${{ secrets.SSH_HOST }} -u ${{ secrets.SSH_USR }} -p ${{ secrets.SSH_PWD }} -b ${{ secrets.SSH_BASE_DIR}}
    - name: Update channel icons
      run: python3 automations/update_channel_icons.py -k ${{ secrets.PRIVATE_YT_API_KEY }} --ssh_host ${{ secrets.SSH_HOST }} -u ${{ secrets.SSH_USR }} -p ${{ secrets.SSH_PWD }} -b ${{ secrets.SSH_BASE_DIR}}
